<!DOCTYPE html>
<html lang="en">
<?php 
include_once('include/header.php');
?>
	<body class=" sidebar-fixed navbar-fixed  loading">
		<div id="initial-loader">
			<div class="initial-loader-bottom">
				Loading. Please Wait. <i class="fa fa-cricle" style="opacity: 0"></i>
			</div>
		</div>

		<!-- Bower Libraries Scripts -->
		<script src="/assets/vendor/js/lib.js"></script>

		<div class="main-wrap">
			<?php include_once('include/nav.php');?>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="sub-navbar sub-navbar__header-breadcrumbs">
							<div class="container-fluid">
								<div class="row">
									<div class="col-lg-12 sub-navbar-column">
										<div class="sub-navbar-header">
											<h3>Home</h3>
										</div>
										<ol class="breadcrumb navbar-text navbar-right no-bg">
											<li class="current-parent">
												<a class="current-parent" href="/">
													<i class="fa fa-fw fa-home"></i>
												</a>
											</li>
											<li>
												<a href="javascript: void(0)">
													Over All Data
												</a>
											</li>
											<li class="active">Right here!</li>
										</ol>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						
					</div>
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total Orders <small class="pull-right text-gray-lighter">last updated date -></small></div>
								<div class="panel-body">
									
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total Volume <small class="pull-right text-gray-lighter">last updated date -></small></div>
								<div class="panel-body">
									
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total ISK <small class="pull-right text-gray-lighter">last updated date -></small></div>
								<div class="panel-body">
									
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-lg-3 col-md-3 col-sm-3">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">Sell Region</label>
									<div class="col-sm-8">
										<select id="sellRegion" name="sellRegion"  class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">Buy Region</label>
									<div class="col-sm-8">
										<select id="buyRegion" name="buyRegion"  class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							
						</div>
					</div>

					<div class="row">
						<div class="col-lg-3 col-md-3 col-sm-3">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">Select Catagory</label>
									<div class="col-sm-8">
										<select id="catagory" name="catagory" onchange="javascript:getGroups();" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">Select Group</label>
									<div class="col-sm-8">
										<select id="group" name="group" onchange="javascript:getItems();" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">Select Item</label>
									<div class="col-sm-8">
										<select id="item" name="item" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							<!-- <a href="javascript:runIt()" class="btn btn-success">Run it</a> -->
						</div>
					</div>

					<div class="row">
						<div class="col-lg-12">
							<ul class="nav nav-tabs nav-justified">
								<li class="nav-item">
									<a class="nav-link active" data-toggle="tab" href="#tab1" role="tab">Region Categories</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab2" role="tab">Category Groups</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab3" role="tab">Group Items</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab4" role="tab">Items Orders</a>
								</li>
								<!-- <li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab5" role="tab">Orders </a>
								</li> -->
							</ul>
							<div class="tab-content">
								<div class="tab-pane active" id="tab1" role="tabpanel">
									<!-- <div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<a href="javascript:getCatByOrders();" class="btn btn-primary">Load Buy Orders</a>
										</div>
									</div> -->
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Region Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holderRegionSell">
													<table id="tableRegionSell" class="display table">
														<thead>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Region Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holderRegionBuy">
													<table id="tableRegionBuy" class="display table">
														<thead>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab2" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Group Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder3">
													<table id="tableGroupSell" class="display table">
														<thead>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Group Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder4">
													<table id="tableGroupBuy" class="display table">
														<thead>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab3" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder5">
													<table id="tableItemSell" class="display table">
														<thead>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder6">
													<table id="tableItemBuy" class="display table">
														<thead>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab4" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder7">
													<!-- <table id="tableOrderSell" class="display table">
														<thead>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table> -->
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder8">
													
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- <div class="tab-pane" id="tab5" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">none yet <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holdernone">
													
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">none <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holdernone2">
													
												</div>
											</div>
										</div>
									</div>
								</div> -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<script src="/assets/vendor/js/jquery.dataTables.js"></script>
			<script src="/assets/vendor/js/datatables.bootstrap.js"></script>
			<?php include_once('include/footer.php');?>
		</div>
		<script>
			// Hide loader
			(function() {
				var bodyElement = document.querySelector('body');
				bodyElement.classList.add('loading');

				document.addEventListener('readystatechange', function() {
					if(document.readyState === 'complete') {
						var bodyElement = document.querySelector('body');
						var loaderElement = document.querySelector('#initial-loader');

						bodyElement.classList.add('loaded');
						setTimeout(function() {
							bodyElement.removeChild(loaderElement);
							bodyElement.classList.remove('loading', 'loaded');
						}, 200);
					}
				});
			})();

			/*$.get('/data/home/catBuyOrdersSum', function(data) {
				$('#holder1').html(data);
			});

			$.get('/data/home/catSellOrdersSum', function(data) {
				$('#holder2').html(data);
			});*/


			var table1 = $('#tableRegionSell').DataTable();
			var table2 = $('#tableRegionBuy').DataTable();
			var table3 = $('#tableGroupSell').DataTable();
			var table4 = $('#tableGroupBuy').DataTable();
			var table5 = $('#tableItemSell').DataTable();
			var table6 = $('#tableItemBuy').DataTable();

			$('#sellRegion').on('change', function(event) {
				event.preventDefault();
				var regionId = $(this).val();
				if(regionId != -1){
					table1.destroy();
					$.get('/data/home/catOrdersSum', {regionId:regionId,byOrder:0 }, function(data) {
						// $('#tableRegionSell').html(data);
						var json = jQuery.parseJSON(data);
						// console.log(json);
						table1 = $('#tableRegionSell').DataTable( {
							data: json,
							"columns": [
								{ "data": "category_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					});
				}
			});

			$('#buyRegion').on('change', function(event) {
				event.preventDefault();
				var regionId = $(this).val();
				if(regionId != -1){
					table2.destroy();
					$.get('/data/home/catOrdersSum', {regionId:regionId,byOrder:1 }, function(data) {
						// $('#tableRegionSell').html(data);
						var json = jQuery.parseJSON(data);
						// console.log(json);
						table2 = $('#tableRegionBuy').DataTable( {
							data: json,
							"columns": [
								{ "data": "category_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					});
				}
			});

			function loadCatBuyTable(regionId){
				$.get('/data/home/catOrdersSum', {byOrder:1, regionId:regionId},function(data) {
					$('#holder2').html(data);
				});
			}

			function getCatSellTable(regionId){
				$.get('/data/home/catOrdersSum',{byOrder:0, regionId:regionId}, function(data) {
					$('#holder1').html(data);
				});
			}

			function getRegions(){
				$.get('/data/home/getRegions', function(data) {
					// console.log(data);
					var json = jQuery.parseJSON(data);
					$('#sellRegion').append($("<option></option>").attr("value", "-1").text("Select Region"));
					$('#buyRegion').append($("<option></option>").attr("value", "-1").text("Select Region"));
					$('#sellRegion').append($("<option></option>").attr("value", "All").text("All Regions"));
					$('#buyRegion').append($("<option></option>").attr("value", "All").text("All Regions"));
					$.each(json, function(index, val) {
						// console.log(val.regionId);
						$('#sellRegion').append($("<option></option>").attr("value", val.regionId).text(val.name));
						$('#buyRegion').append($("<option></option>").attr("value", val.regionId).text(val.name));
					});
				});
			}

			function getCatagory(){
				$.get('/data/home/getCatagories', function(data) {
					var json = jQuery.parseJSON(data);
					$('#catagory').append($("<option></option>").attr("value", "All").text("All Categories"));
					$.each(json, function(index, val) {
						$('#catagory').append($("<option></option>").attr("value", val.catagoryId).text(val.name));
					});
				});
			}

			function getGroups(){
				var catagoryId = $('#catagory').val();
				var buyRegionId = $('#buyRegion').val();
				var sellRegionId = $('#sellRegion').val();

				$("#group").empty();
				$("#item").empty();
				$.get('/getGroupsByCatagory',{catagoryId:catagoryId}, function(data) {
					var json = jQuery.parseJSON(data);
					$('#group').append($("<option></option>").attr("value", "All").text("Select Group"));
					$.each(json, function(index, val) {
						$('#group').append($("<option></option>").attr("value", val.groupId).text(val.name));
					});
				});

				/*$.get('/data/home/groupOrders',{catagoryId:catagoryId, regionId:sellRegionId, byOrder:1 }, function(data) {
					$('#holder3').html(data);
				});

				$.get('/data/home/groupOrders',{catagoryId:catagoryId, regionId:buyRegionId, byOrder:0 }, function(data) {
					$('#holder4').html(data);
				});*/

				table3.destroy();
				$.get('/data/home/groupOrders', {catagoryId:catagoryId, regionId:sellRegionId, byOrder:0 }, function(data) {
					// $('#tableRegionSell').html(data);
					var json = jQuery.parseJSON(data);
					// console.log(json);
					table3 = $('#tableGroupSell').DataTable( {
						data: json,
						"columns": [
							{ "data": "group_name" },
							{ "data": "Total Volume" },
							{ "data": "Total Volume Remaining" },
							{ "data": "Total Orders" },
							{ "data": "Total ISK" }
						]
					});
				});

				table4.destroy();
				$.get('/data/home/groupOrders', {catagoryId:catagoryId, regionId:buyRegionId, byOrder:1 }, function(data) {
					// $('#tableRegionSell').html(data);
					var json = jQuery.parseJSON(data);
					// console.log(json);
					table3 = $('#tableGroupBuy').DataTable( {
						data: json,
						"columns": [
							{ "data": "group_name" },
							{ "data": "Total Volume" },
							{ "data": "Total Volume Remaining" },
							{ "data": "Total Orders" },
							{ "data": "Total ISK" }
						]
					});
				});

			}

			function getItems(){
				var groupId = $('#group').val();
				var catagoryId = $('#catagory').val();
				// var regionId = $('#region').val();
				var buyRegionId = $('#buyRegion').val();
				var sellRegionId = $('#sellRegion').val();

				$("#item").empty();
				$.get('/getItemsByGroup',{groupId:groupId}, function(data) {
					var json = jQuery.parseJSON(data);
					$('#item').append($("<option></option>").attr("value", "All").text("Select Item"));
					$.each(json, function(index, val) {
						$('#item').append($("<option></option>").attr("value", val.itemId).text(val.name));
					});
				});

				table5.destroy();
				$.get('/data/home/itemOrders',{catagoryId:catagoryId, regionId:sellRegionId, groupId:groupId, byOrder:0 }, function(data) {
					var json = jQuery.parseJSON(data);
					table5 = $('#tableItemSell').DataTable( {
						data: json,
						"columns": [
							{ "data": "item_name" },
							{ "data": "Total Volume" },
							{ "data": "Total Volume Remaining" },
							{ "data": "Total Orders" },
							{ "data": "Total ISK" }
						]
					});
				});

				table6.destroy();
				$.get('/data/home/itemOrders',{catagoryId:catagoryId, regionId:buyRegionId, groupId:groupId, byOrder:1 }, function(data) {
					var json = jQuery.parseJSON(data);
					// console.log(json);
					table6 = $('#tableItemBuy').DataTable( {
						data: json,
						"columns": [
							{ "data": "item_name" },
							{ "data": "Total Volume" },
							{ "data": "Total Volume Remaining" },
							{ "data": "Total Orders" },
							{ "data": "Total ISK" }
						]
					});
				});
			}

			// function regionChange(){
				// var regionId = $('#region').val();
				// loadCatBuyTable(regionId);
				// getCatSellTable(regionId);
			// }

			/*function runIt(){
				var buyRegionId = $('#region').val();
				var sellRegionId = $('#region2').val();
				loadCatBuyTable(buyRegionId);
				getCatSellTable(sellRegionId);
			}*/

			$(document).ready(function() {
				getRegions();
				getCatagory();
				/* load everything off the bat */
				// loadCatBuyTable("All");
				// getCatSellTable("All");
			});

		</script>
		<!-- Bower Libraries Styles -->
		<link rel="stylesheet" href="/assets/vendor/css/lib.css">

		<script src="/js/app.js"></script>

		<script src="/js/plugins-init.js"></script>
		<script src="/js/switchery-settings.js"></script>
	</body>
</html