<!DOCTYPE html>
<html lang="en">
<?php 
include_once('include/header.php');
?>
	<body class=" sidebar-fixed navbar-fixed sidebar-slim loading">
		<div id="initial-loader">
			<div class="initial-loader-bottom">
				Loading. Please Wait. <i class="fa fa-cricle" style="opacity: 0"></i>
			</div>
		</div>

		<!-- Bower Libraries Scripts -->
		<script src="/assets/vendor/js/lib.js"></script>

		<div class="main-wrap">
			<?php include_once('include/nav.php');?>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="sub-navbar sub-navbar__header-breadcrumbs">
							<div class="container-fluid">
								<div class="row">
									<div class="col-lg-12 sub-navbar-column">
										<div class="sub-navbar-header">
											<h3>Home</h3>
										</div>
										<ol class="breadcrumb navbar-text navbar-right no-bg">
											<li class="current-parent">
												<a class="current-parent" href="/">
													<i class="fa fa-fw fa-home"></i>
												</a>
											</li>
											<li>
												<a href="javascript: void(0)">
													Metz's Market Exploration
												</a>
											</li>
											Easy as 
											<span class="badge badge-heliotrope">1</span>
											<span class="badge badge-dodger-blue">2</span>
											<span class="badge badge-malibu">3</span>
											<span class="badge badge-aquamarine">4</span>
											<span class="badge badge-mint-green">5</span>
										</ol>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						
					</div>
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total Orders </div>
								<div class="panel-body">
									<table class="table table-bordered table-hover table-striped table-responsive">
										<tr>
											<td>Orders to Buy</td>
											<td>Orders to Sell</td>
										</tr>
										<tr>
											<td> <div id="holdOBCount"></div></td>
											<td> <div id="holdOSCount">0</div></td>
										</tr>
									</table>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total Volume </div>
								<div class="panel-body">
									<table class="table table-bordered table-hover table-striped table-responsive">
										<tr>
											<td>Orders to Buy</td>
											<td>Orders to Sell</td>
										</tr>
										<tr>
											<td> <div  id="holdOBVolume">0</div></td>
											<td> <div  id="holdOSVolume">0</div></td>
										</tr>
									</table>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Total ISK </div>
								<div class="panel-body">
									<table class="table table-bordered table-hover table-striped table-responsive">
										<tr>
											<td>Cost to Purchase</td>
											<td>After Sold</td>
											<td>Revenue</td>
										</tr>
										<tr>
											<td> <div id="holdOBPrice">0</div></td>
											<td> <div id="holdOSPrice">0</div></td>
											<td> <div id="holdRevenu">0</div></td>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4">
							
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">
										Where to buy
										<span>
											<i class=" fa fa-lg fa-fw fa-check-square"></i>
											<span class="badge badge-heliotrope badge-with-icon ">1</span>
										</span>
									</label>
									<div class="col-sm-8">
										<select id="sellRegion" name="sellRegion"  class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">
										Where to sell
									<span>
										<i class=" fa fa-lg fa-fw fa-check-square"></i>
										<span class="badge badge-dodger-blue badge-with-icon ">2</span>
									</span>
									</label>
									<div class="col-sm-8">
										<select id="buyRegion" name="buyRegion"  class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">

						</div>
					</div>

					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">
										Catagory
										<span>
											<i class=" fa fa-lg fa-fw fa-check-square"></i>
											<span class="badge badge-malibu badge-with-icon ">3</span>
										</span>
									</label>
									<div class="col-sm-8">
										<select id="catagory" name="catagory" onchange="javascript:getGroups();" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label">
										Group
										<span>
											<i class=" fa fa-lg fa-fw fa-check-square"></i>
											<span class="badge badge-aquamarine badge-with-icon ">4</span>
										</span>
									</label>
									<div class="col-sm-8">
										<select id="group" name="group" onchange="javascript:getItems();" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<form class="form-horizontal">
								<div class="form-group">
									<label class="col-sm-4 control-label text-left">
										Item
										<span>
											<i class=" fa fa-lg fa-fw fa-check-square"></i>
											<span class="badge badge-mint-green badge-with-icon ">5</span>
										</span>
									</label>
									<div class="col-sm-8">
										<select id="item" name="item" class="form-control">
											
										</select>
									</div>
								</div>
							</form>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3">
							<!-- <a href="javascript:runIt()" class="btn btn-success">Run it</a> -->
						</div>
					</div>

					<div class="row">
						<div class="col-lg-12" id="tabs">
							<ul class="nav nav-tabs nav-justified">
								<li class="nav-item">
									<a class="nav-link active" data-toggle="tab" href="#tab1" role="tab">
										<span class="badge badge-heliotrope">1</span> &amp;
										<span class="badge badge-dodger-blue">2</span>
										Region Categories
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab2" role="tab">
										<span class="badge badge-malibu">3</span>
										Category Groups
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab3" role="tab">
										<span class="badge badge-aquamarine">4</span>
										Group Items
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab4" role="tab">
										<span class="badge badge-mint-green">5</span>
										Items Orders
									</a>
								</li>
								<!-- <li class="nav-item">
									<a class="nav-link " data-toggle="tab" href="#tab5" role="tab">Orders </a>
								</li> -->
							</ul>
							<div class="tab-content">
								<div class="tab-pane active" id="tab1" role="tabpanel">
									<!-- <div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<a href="javascript:getCatByOrders();" class="btn btn-primary">Load Buy Orders</a>
										</div>
									</div> -->
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Region Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holderRegionSell">
													<table id="tableRegionSell" class="display table">
														<thead>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Region Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holderRegionBuy">
													<table id="tableRegionBuy" class="display table">
														<thead>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Category Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab2" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Group Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder3">
													<table id="tableGroupSell" class="display table">
														<thead>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Group Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder4">
													<table id="tableGroupBuy" class="display table">
														<thead>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Group Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab3" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder5">
													<table id="tableItemSell" class="display table">
														<thead>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder6">
													<table id="tableItemBuy" class="display table">
														<thead>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</thead>
														<tfoot>
															<tr>
																<th>Item Name</th>
																<th>Total Volume</th>
																<th>Total Volume Remaining</th>
																<th>Total Orders</th>
																<th>Total isk</th>
															</tr>
														</tfoot>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="tab4" role="tabpanel">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Sell Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder7">
													
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="panel panel-default b-a-0 bg-gray-dark">
												<div class="panel-heading">Items Buy Orders <small class="pull-right text-gray-lighter"></small></div>
												<div class="panel-body" id="holder8">
													
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<script src="/assets/vendor/js/jquery.dataTables.js"></script>
			<script src="/assets/vendor/js/datatables.bootstrap.js"></script>
			<script src="/assets/vendor/js/toastr.js"></script>
			<?php include_once('include/footer.php');?>
		</div>
		<script>
			// Hide loader
			(function() {
				var bodyElement = document.querySelector('body');
				bodyElement.classList.add('loading');

				document.addEventListener('readystatechange', function() {
					if(document.readyState === 'complete') {
						var bodyElement = document.querySelector('body');
						var loaderElement = document.querySelector('#initial-loader');

						bodyElement.classList.add('loaded');
						setTimeout(function() {
							bodyElement.removeChild(loaderElement);
							bodyElement.classList.remove('loading', 'loaded');
						}, 200);
					}
				});
			})();

			/*$.get('/data/home/catBuyOrdersSum', function(data) {
				$('#holder1').html(data);
			});

			$.get('/data/home/catSellOrdersSum', function(data) {
				$('#holder2').html(data);
			});*/
			

			var table1 = $('#tableRegionSell').DataTable();
			var table2 = $('#tableRegionBuy').DataTable();
			var table3 = $('#tableGroupSell').DataTable();
			var table4 = $('#tableGroupBuy').DataTable();
			var table5 = $('#tableItemSell').DataTable();
			var table6 = $('#tableItemBuy').DataTable();

			$('#sellRegion').on('change', function(event) {
				event.preventDefault();
				var regionId = $(this).val();
				if(regionId != -1){
					table1.destroy();
					$.get('/data/home/catOrdersSum', {regionId:regionId,byOrder:0 }, function(data) {
						// $('#tableRegionSell').html(data);
						var json = jQuery.parseJSON(data);
						// console.log(json);
						table1 = $('#tableRegionSell').DataTable( {
							data: json,
							"columns": [
								{ "data": "category_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					});
				}
			});

			$('#buyRegion').on('change', function(event) {
				event.preventDefault();
				var regionId = $(this).val();
				if(regionId != -1){
					table2.destroy();
					$.get('/data/home/catOrdersSum', {regionId:regionId,byOrder:1 }, function(data) {
						// $('#tableRegionSell').html(data);
						var json = jQuery.parseJSON(data);
						// console.log(json);
						table2 = $('#tableRegionBuy').DataTable( {
							data: json,
							"columns": [
								{ "data": "category_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					});
				}
			});

			function loadCatBuyTable(regionId){
				$.get('/data/home/catOrdersSum', {byOrder:1, regionId:regionId},function(data) {
					$('#holder2').html(data);
				});
			}

			function getCatSellTable(regionId){
				$.get('/data/home/catOrdersSum',{byOrder:0, regionId:regionId}, function(data) {
					$('#holder1').html(data);
				});
			}

			function getRegions(){
				$.get('/data/home/getRegions', function(data) {
					// console.log(data);
					var json = jQuery.parseJSON(data);
					$('#sellRegion').append($("<option></option>").attr("value", "-1").text("Select Region"));
					$('#buyRegion').append($("<option></option>").attr("value", "-1").text("Select Region"));
					$('#sellRegion').append($("<option></option>").attr("value", "All").text("All Regions"));
					$('#buyRegion').append($("<option></option>").attr("value", "All").text("All Regions"));
					$.each(json, function(index, val) {
						// console.log(val.regionId);
						$('#sellRegion').append($("<option></option>").attr("value", val.regionId).text(val.name));
						$('#buyRegion').append($("<option></option>").attr("value", val.regionId).text(val.name));
					});
				});
			}

			function getCatagory(){
				$.get('/data/home/getCatagories', function(data) {
					var json = jQuery.parseJSON(data);
					$('#catagory').append($("<option></option>").attr("value", "All").text("All Categories"));
					$.each(json, function(index, val) {
						$('#catagory').append($("<option></option>").attr("value", val.catagoryId).text(val.name));
					});
				});
			}

			function getGroups(){
				var catagoryId = $('#catagory').val();
				var buyRegionId = $('#buyRegion').val();
				var sellRegionId = $('#sellRegion').val();

				$("#group").empty();
				$("#item").empty();
				$.get('/getGroupsByCatagory',{catagoryId:catagoryId}, function(data) {
					var json = jQuery.parseJSON(data);
					$('#group').append($("<option></option>").attr("value", "All").text("Select Group"));
					$.each(json, function(index, val) {
						$('#group').append($("<option></option>").attr("value", val.groupId).text(val.name));
					});
				});

				/*$.get('/data/home/groupOrders',{catagoryId:catagoryId, regionId:sellRegionId, byOrder:1 }, function(data) {
					$('#holder3').html(data);
				});

				$.get('/data/home/groupOrders',{catagoryId:catagoryId, regionId:buyRegionId, byOrder:0 }, function(data) {
					$('#holder4').html(data);
				});*/

				// table3.destroy();
				$.get('/data/home/groupOrders', {catagoryId:catagoryId, regionId:sellRegionId, byOrder:0 }, function(data) {
					// $('#tableRegionSell').html(data);
					var json = jQuery.parseJSON(data);

					if(Object.keys(json).length != 0){
						// alert('inhere');
						table3.destroy();
						table3 = $('#tableGroupSell').DataTable( {
							data: json,
							"columns": [
								{ "data": "group_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					}else{
						table3.clear().draw();
					}
					
				});

				// table4.destroy();
				$.get('/data/home/groupOrders', {catagoryId:catagoryId, regionId:buyRegionId, byOrder:1 }, function(data) {
					// $('#tableRegionSell').html(data);
					var json = jQuery.parseJSON(data);
					// console.log(json);
					if(Object.keys(json).length != 0){
						// alert('inhere');
						table4.destroy();
						table4 = $('#tableGroupBuy').DataTable( {
							data: json,
							"columns": [
								{ "data": "group_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					}else{
						table4.clear().draw();
					}
				});

				activaTab("tab2");
			}

			function getItems(){
				var groupId = $('#group').val();
				var catagoryId = $('#catagory').val();
				// var regionId = $('#region').val();
				var buyRegionId = $('#buyRegion').val();
				var sellRegionId = $('#sellRegion').val();

				$("#item").empty();
				$.get('/getItemsByGroup',{groupId:groupId}, function(data) {
					var json = jQuery.parseJSON(data);
					$('#item').append($("<option></option>").attr("value", "All").text("Select Item"));
					$.each(json, function(index, val) {
						$('#item').append($("<option></option>").attr("value", val.itemId).text(val.name));
					});
				});

				// table5.destroy();
				$.get('/data/home/itemOrders',{catagoryId:catagoryId, regionId:sellRegionId, groupId:groupId, byOrder:0 }, function(data) {
					var json = jQuery.parseJSON(data);
					
					if(Object.keys(json).length != 0){
						table5.destroy();
						table5 = $('#tableItemSell').DataTable( {
							data: json,
							"columns": [
								{ "data": "item_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					}else{
						table5.clear().draw();
					}
				});

				// table6.destroy();
				$.get('/data/home/itemOrders',{catagoryId:catagoryId, regionId:buyRegionId, groupId:groupId, byOrder:1 }, function(data) {
					var json = jQuery.parseJSON(data);
					// console.log(json);
					if(Object.keys(json).length != 0){
						table6.destroy();
						table6 = $('#tableItemBuy').DataTable( {
							data: json,
							"columns": [
								{ "data": "item_name" },
								{ "data": "Total Volume" },
								{ "data": "Total Volume Remaining" },
								{ "data": "Total Orders" },
								{ "data": "Total ISK" }
							]
						});
					}else{
						table6.clear().draw();
					}
				});
				activaTab("tab3");
			}

			$("#item").on('change', function(event) {
				event.preventDefault();
				var buyRegionId = $('#buyRegion').val();
				var sellRegionId = $('#sellRegion').val();
				var typeId = $(this).val();
				$.get('/data/home/getOrders', {regionId:sellRegionId, typeId:typeId, buyOrder:0}, function(data) {
					$('#holder7').html(data);
				});

				$.get('/data/home/getOrders', {regionId:buyRegionId, typeId:typeId, buyOrder:1}, function(data) {
					$('#holder8').html(data);
				});
				activaTab("tab4");
			});

			$(document).ready(function() {
				getRegions();
				getCatagory();
			});

			function activaTab(tab){
				$('.nav-tabs a[href="#' + tab + '"]').tab('show');
			};

			var buyOrders = 0; var sellOrders = 0;
			var totalBuy = 0; var totalSell = 0;
			var totalBuyVolume = 0; var totalSellVolume = 0;

			function addOrder(id, volRemain, price, isBuy){
				// console.log(isBuy);
				// volRemain = parseInt(volRemain, 10);
				volRemain = toFixed(volRemain);
				console.log(volRemain);
				price = toFixed(price);
				console.log(price);
				if(isBuy == 0){  // sell to
					buyOrders++;
					totalBuy += volRemain*price;
					totalBuyVolume += volRemain;
					$('#holdOBCount').html(buyOrders);
					$('#holdOBVolume').html(totalBuyVolume);
					$('#holdOBPrice').html(totalBuy);
					var rev = totalSell-totalBuy;
					$('#holdRevenu').html(rev);
					$('#'+id).html("");
				}else{ // buy from
					sellOrders++;
					totalSell += volRemain*price;
					totalSellVolume += volRemain;
					$('#holdOSCount').html(sellOrders);
					$('#holdOSVolume').html(totalSellVolume);
					$('#holdOSPrice').html(totalSell);
					var rev = totalSell-totalBuy;
					$('#holdRevenu').html(rev);
					$('#'+id).html("");
				}
			};


			function toFixed(x) {
			  if (Math.abs(x) < 1.0) {
				var e = parseInt(x.toString().split('e-')[1]);
				if (e) {
					x *= Math.pow(10,e-1);
					x = '0.' + (new Array(e)).join('0') + x.toString().substring(2);
				}
			  } else {
				var e = parseInt(x.toString().split('+')[1]);
				if (e > 20) {
					e -= 20;
					x /= Math.pow(10,e);
					x += (new Array(e+1)).join('0');
				}
			  }
			  return x;
			}
		</script>
		<!-- Bower Libraries Styles -->
		<link rel="stylesheet" href="/assets/vendor/css/lib.css">

		<script src="/js/app.js"></script>

		<script src="/js/plugins-init.js"></script>
		<script src="/js/switchery-settings.js"></script>
	</body>
</html