<!DOCTYPE html>
<html lang="en">
<?php 
include_once('include/header.php');
?>
	<body class=" sidebar-fixed navbar-fixed sidebar-slim loading">
		<div id="initial-loader">
			<div class="initial-loader-bottom">
				Loading. Please Wait. <i class="fa fa-cricle" style="opacity: 0"></i>
			</div>
		</div>

		<!-- Bower Libraries Scripts -->
		<script src="/assets/vendor/js/lib.js"></script>

		<div class="main-wrap">
			<?php include_once('include/nav.php');?>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="sub-navbar sub-navbar__header-breadcrumbs">
							<div class="container-fluid">
								<div class="row">
									<div class="col-lg-12 sub-navbar-column">
										<div class="sub-navbar-header">
											<h3>Search</h3>
										</div>
										<ol class="breadcrumb navbar-text navbar-right no-bg">
											<li class="current-parent">
												<a class="current-parent" href="/">
													<i class="fa fa-fw fa-home"></i>
												</a>
											</li>
											<li>
												<a href="javascript: void(0)">
													All Market Orders
												</a>
											</li>
											
										</ol>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Group Information </div>
								<div class="panel-body" id="groupDescription">
									
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Item Description </div>
								<div class="panel-body" id="itemDescription">
									
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Another space </div>
								<div class="panel-body" id="tmp2">
									
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-8">
							<table id="moneyMakers" class="display table">
								<thead>
									<tr>
										<th>Type Id</th>
										<th>Name</th>
										<th>Average Price</th>
										<th>Adjusted Price</th>
										<th>Profit</th>
									</tr>
								</thead>
								<tfoot>
									<tr>
										<th>Type Id</th>
										<th>Name</th>
										<th>Average Price</th>
										<th>Adjusted Price</th>
										<th>Profit</th>
									</tr>
								</tfoot>
							</table>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-4">
							<div class="panel panel-default b-a-0 bg-gray-dark">
								<div class="panel-heading">Blue Print Data </div>
								<div class="panel-body" id="bluePrintData">
									
								</div>
							</div>
						</div>
					</div>
				</div>
				<script src="/assets/vendor/js/jquery.dataTables.js"></script>
				<script src="/assets/vendor/js/datatables.bootstrap.js"></script>
				<script type="text/javascript">
					$(document).ready(function() {
						$('#moneyMakers').DataTable( {
							"processing": true,
							"serverSide": true,
							"ajax": "/db/moneyMakers",
							"order": [[ 4, "desc" ]]
						} );
					} );

					function getItemDetails(id){
						$('#bluePrintData').html("");
						// var json;
						if(id){
							/*$.get('/moneyMakers/getSubItems/'+id, function(data) {
								json = jQuery.parseJSON(data);
								// $('#detailHolder').html(json.description);
								$('#itemDescription').html(json.description);
							}).done(function(){
								console.log(json.group_id);
								console.log(json.market_group_id);
							});*/
							$.ajax({
								url: '/moneyMakers/getSubItems/'+id,
								type: 'GET',
								dataType: 'JSON',
							})
							.done(function(data) {
								console.log("success");
								$('#itemDescription').html(data.description);
								console.log(data.group_id);
								getGroupInfo(data.group_id);
								console.log(data.market_group_id);

								$.get('/moneyMakers/getBluePrint/'+id, function(data2) {
									$('#bluePrintData').html(data2);
								});
							})
							.fail(function() {
								console.log("error");
							})
							.always(function() {
								console.log("complete");
							});
							
						}
					};

					function getGroupInfo(groupId){
						if(groupId){
							$.get('/moneyMakers/getGroups/'+groupId, function(data) {
								var json = jQuery.parseJSON(data);
								console.log(json);
							});
						}
					};
				</script>
			</div>
			<?php include_once('include/footer.php');?>
		</div>
		<script>
			// Hide loader
			(function() {
				var bodyElement = document.querySelector('body');
				bodyElement.classList.add('loading');

				document.addEventListener('readystatechange', function() {
					if(document.readyState === 'complete') {
						var bodyElement = document.querySelector('body');
						var loaderElement = document.querySelector('#initial-loader');

						bodyElement.classList.add('loaded');
						setTimeout(function() {
							bodyElement.removeChild(loaderElement);
							bodyElement.classList.remove('loading', 'loaded');
						}, 200);
					}
				});
			})();
		</script>

		<!-- Bower Libraries Styles -->
		<link rel="stylesheet" href="/assets/vendor/css/lib.css">

		<script src="/js/app.js"></script>

		<script src="/js/plugins-init.js"></script>
		<script src="/js/switchery-settings.js"></script>
	</body>
</html