
<!DOCTYPE html>
<html lang="en">
 <!-- START Head -->
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<!-- Enable responsiveness on mobile devices-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

	<title>
		EVE Online Market Tools
	</title>

	<!--START Loader -->
	<style>
		#initial-loader{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;width:100%;background:#212121;position:fixed;z-index:10000;top:0;left:0;bottom:0;right:0;transition:opacity .2s ease-out}#initial-loader .initial-loader-top{display:flex;align-items:center;justify-content:space-between;width:200px;border-bottom:1px solid #2d2d2d;padding-bottom:5px}#initial-loader .initial-loader-top > *{display:block;flex-shrink:0;flex-grow:0}#initial-loader .initial-loader-bottom{padding-top:10px;color:#5C5C5C;font-family:-apple-system,"Helvetica Neue",Helvetica,"Segoe UI",Arial,sans-serif;font-size:12px}@keyframes spin{100%{transform:rotate(360deg)}}#initial-loader .loader g{transform-origin:50% 50%;animation:spin .5s linear infinite}body.loading {overflow: hidden !important} body.loaded #initial-loader{opacity:0}
	</style>
	<!--END Loader-->

	<!-- SCSS Output -->
	<link rel="stylesheet" href="assets/stylesheets/app.css">

	<!-- START Favicon -->
	<link rel="apple-touch-icon" sizes="57x57" href="../assets/images/favicons/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="../assets/images/favicons/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="../assets/images/favicons/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="../assets/images/favicons/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="../assets/images/favicons/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="../assets/images/favicons/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="../assets/images/favicons/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="../assets/images/favicons/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="../assets/images/favicons/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192" href="../assets/images/favicons/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="../assets/images/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="../assets/images/favicons/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicons/favicon-16x16.png">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="../assets/images/favicons/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
	<!-- END Favicon -->

	<!-- RSS -->
	<!-- <link rel="alternate" type="application/rss+xml" title="RSS" href="../atom.xml"> -->

	<!-- jekyll settings -->
	<script>
		var ASSET_PATH_BASE = '../';
	</script>
</head>
<!-- END Head -->


	<body class=" footer-disabled  loading">
		<div id="initial-loader">
			<div class="initial-loader-bottom">
				Loading. Please Wait. <i class="fa fa-cricle" style="opacity: 0"></i>
			</div>
		</div>

		<!-- Bower Libraries Scripts -->
		<script src="assets/vendor/js/lib.js"></script>

		<div class="main-wrap">
			<nav class="navigation">
				<!-- START Navbar -->
				<div class="navbar-inverse navbar navbar-fixed-top">
					<div class="container-fluid">

						<div class="navbar-header">
							<a class="current navbar-brand" href="#">
								<img alt="Metz Logo" class="h-20" src="assets/images/logo.png">
							</a>
							<button class="action-right-sidebar-toggle navbar-toggle collapsed" data-target="#navdbar" data-toggle="collapse" type="button">
								<i class="fa fa-fw fa-align-right text-white"></i>
							</button>
							<button class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
								<i class="fa fa-fw fa-user text-white"></i>
							</button>
							<button class="action-sidebar-open navbar-toggle collapsed" type="button">
								<i class="fa fa-fw fa-bars text-white"></i>
							</button>
						</div>

						<div class="collapse navbar-collapse" id="navbar">

							<!-- START Search Mobile -->
							<div class="form-group hidden-lg hidden-md hidden-sm">
								<div class="input-group hidden-lg hidden-md">
									<input type="text" class="form-control" placeholder="Search for...">
									<span class="input-group-btn">
										<button class="btn btn-primary" type="button"><i class="fa fa-fw fa-search"></i></button>
									</span>
								</div>
							</div>
							<!-- END Search Mobile -->

							<!-- START Left Side Navbar -->
							<ul class="nav navbar-nav navbar-left clearfix yamm">

								<!-- START Switch Sidebar ON/OFF -->
								<li id="sidebar-switch" class="hidden-xs">
									<a class="action-toggle-sidebar-slim" data-placement="bottom" data-toggle="tooltip" href="#" title="Slim sidebar on/off">
										<i class="fa fa-lg fa-bars fa-fw"></i>
									</a>
								</li>
								<!-- END Switch Sidebar ON/OFF -->

								<!-- START Menu Only Visible on Navbar -->
								<li id="top-menu-switch" class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <i class="fa fa-fw fa-caret-down"></i></a>
									
								</li>
								<!-- END Menu Only Visible on Navbar -->


								<li class="spin-search-box clearfix hidden-xs">
									<a href="#" class="pull-left">
										<i class="fa fa-search fa-lg icon-inactive"></i>
										<i class="fa fa-close fa-lg icon-active"></i>
									</a>
									<div class="input-group input-group-sm pull-left p-10">
										<input type="text" class="form-control" placeholder="Search for...">
										<span class="input-group-btn">
											<button class="btn btn-primary" type="button">
												<i class="fa fa-search"></i>
											</button>
										</span>
									</div>
								</li>
							</ul>
							<!-- START Left Side Navbar -->
						</div>
					</div>
				</div>
				<!-- END Navbar -->

			</nav>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<h1>Select Area</h1>
					</div>
					<div class="row">
						
						<div class="col-md-2">
							<select class="form-control" id="area" name="area">
								<option>One</option>
								<option>Two</option>
								<option>Three</option>
								<option>Four</option>
								<option>Five</option>
							</select>
						</div>
					</div>
				</div>

			</div>
			 <!-- START Footer -->
			<footer>
				<div class="container-fluid">
					<p class="text-gray-dark">
						<strong class="m-r-1">SPIN Dashboard </strong> 
						<span class="text-gray-dark">&#xA9; 2009 - 2016. Made by 
						<i class="fa fa-fw fa-heart text-danger"></i> New York, US</span>
					</p>
				</div>
			</footer>
			<!-- END Footer -->

		</div>
		<script>
			// Hide loader
			(function() {
				var bodyElement = document.querySelector('body');
				bodyElement.classList.add('loading');

				document.addEventListener('readystatechange', function() {
					if(document.readyState === 'complete') {
						var bodyElement = document.querySelector('body');
						var loaderElement = document.querySelector('#initial-loader');

						bodyElement.classList.add('loaded');
						setTimeout(function() {
							bodyElement.removeChild(loaderElement);
							bodyElement.classList.remove('loading', 'loaded');
						}, 200);
					}
				});
			})();
		</script>

		<!-- Bower Libraries Styles -->
		<link rel="stylesheet" href="assets/vendor/css/lib.css">

		<script src="js/app.js"></script>

		<script src="js/plugins-init.js"></script>
		<script src="js/switchery-settings.js"></script>
	</body>

</html>
